### ISSUE TITLE
rollup: emitFile error when importing css files outside of cwd directory

### ISSUE THREAD

**Issue by winixt** [vanilla-extract-css/vanilla-extract#932] opened 2022-11-29 03:32 UTC
### Describe the bug

fileName can transform a short_id ?
![image](https://user-images.githubusercontent.com/20717402/204431869-ce9150ed-248c-47a2-8100-685fe4e59eb7.png)

### Reproduction

not need

### System Info

```shell
rollup: 3.5.0
mac OS
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by graup** [comment] 2022-12-07 05:55
Could you provide a reproduction?

**Comment by winixt** [comment] 2022-12-07 10:02
> Could you provide a reproduction?

@graup https://github.com/winixt/vanilla-extract-bug

**Comment by graup** [comment] 2023-07-17 01:54
This seems to be a problem with `cwd`. If you remove the `cwd` argument or set it to the src directory instead of the hello directory, it works.

Still it should be possible to fix, if someone is interested in opening a PR.

**Comment by askoufis** [comment] 2024-03-02 04:14
IMO this seems more like a misconfiguration issue rather than something worth fixing.

If you wanted to fix this in the rollup plugin, you'd need to convert the relative path `id`, e.g. `../index.css.ts.vanilla.css`, to something valid. You could resolve the relative part of the path to the actual path, e.g. `src/index.css.ts.vanilla.css`, but at that point you've essentially just derived what the `cwd` should have been in the first place, i.e. `src`.

The complexity added by supporting this use case doesn't really seem worth it, especially for something that can be trivially fixed by configuring the plugin correctly. Unless there's some simple way to support this, I don't see why we should.

Please re-open this issue if there's a valid use case for supporting this.

**Closed by askoufis** 2024-03-02 04:14 UTC
Labels: help wanted, rollup
