### ISSUE TITLE
Environment variables not accessible in ".css.ts" files

### ISSUE THREAD

**Issue by 3tmaan** [vanilla-extract-css/vanilla-extract#1202] opened 2023-10-20 16:10 UTC
### Describe the bug

When using Vite in conjunction with Vanilla Extract, I'm unable to access Vite environment variables (defined using the `VITE_` prefix) within `.css.ts` files. While these variables can be accessed within normal `.ts` files without issues, any attempt to retrieve them within `.css.ts` files results in the variable being `undefined`. Additionally, using `import.meta.env` within a `.ts` file that's imported into a `.css.ts` file raises a warning about the output format being "cjs" and that "import.meta" is not available.

### Reproduction

https://codesandbox.io/p/sandbox/priceless-water-t6tsv8

### System Info

```shell
Operating System: macOS
Node version: v18.16.0
Vite version: v4.4.5
Vanilla Extract version: v1.13.0
```

### Used Package Manager

pnpm

### Logs

```shell
Internal server error: Cannot read properties of undefined (reading 'VITE_FONT_BASE_URL')
  Plugin: vanilla-extract
  File: /workspaces/sandbox/src/styles/fonts.css.ts
      at /workspaces/sandbox/src/styles/fonts.css.ts:32:37
      at Script.runInContext (node:vm:134:12)
      at Script.runInNewContext (node:vm:139:17)
      at module.exports [as default] (/workspaces/sandbox/node_modules/eval/eval.js:84:12)
      at Object.processVanillaFile (/workspaces/sandbox/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.dev.js:132:50)
      at TransformContext.transform (/workspaces/sandbox/node_modules/@vanilla-extract/vite-plugin/dist/vanilla-extract-vite-plugin.cjs.dev.js:196:40)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.transform (file:///workspaces/sandbox/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:44345:30)
      at async loadAndTransform (file:///workspaces/sandbox/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:55015:29)
      at async viteTransformMiddleware (file:///workspaces/sandbox/node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:64417:32) (x2)
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/vanilla-extract-css/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by askoufis** [comment] 2023-11-07 11:20
I'm having trouble loading your codesandbox. Is there any chance you could upload the reproduction to github instead?

Regardless, I'm fairly positive as to the cause of both the errors.
- Vanilla Extract compiles `.css.ts` files using `esbuild`, even if your integration is with vite, webpack, etc. `esbuild` has no idea what `VITE_FONT_BASE_URL` is. You could potentially read your `VITE_`-prefixed envars from `.env` into the vite plugin's `esbuildOptions.define` config as a workaround. It would be nice if the vite plugin could do this for you, however I don't think it's possible to access `import.meta.env` from within a vite plugin.
- I _think_ `esbuild`'s output format is being inferred as `cjs`. `import.meta` is only supported in `esm`, so we'd have to update our esbuild config to specify that. I'm not sure if that's something we can do easily/what the consequences of that are. That being said, if you are reading your `.env` file into `define`, you could just define `import.meta.env.VITE_FOO_BAR: "some_value"` and circumvent esbuild checking `import.meta` completely.

**Comment by gkiely** [comment] 2024-08-27 18:56
Also running into this. I use `import.meta.env.DEV` to determine which parts of the code should run in development only.
In the case of using vanilla-extract this might be some development only styles.

The workaround is to check process.env.NODE_ENV but it would be nice if it matched the vite api.

**Comment by askoufis** [comment] 2024-08-28 11:09
@3tmaan Your codesandbox works as of `@vanilla-extract/vite-plugin` v4.x.

@gkiely I tried accessing `import.meta.env.DEV` in the codesandbox as well and it worked fine.

Closing this issue as completed.

**Closed by askoufis** 2024-08-28 11:09 UTC
Labels: vite
